security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'plaintext'
  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    users_in_memory:
      memory:
        users:
          - identifier: '%env(HTTP_BASIC_AUTH_USERNAME)%'
            password: '%env(HTTP_BASIC_AUTH_PASSWORD)%'
            roles: [ ROLE_USER ]
  firewalls:
    firebase:
      pattern: "^/v3/(users|polls)"
      stateless: true
      custom_authenticators:
        - App\Security\FirebaseAuthenticator
    main:
      pattern: ^/
      http_basic: ~
  access_control:
    - { path: ^/v1/language, roles: [ PUBLIC_ACCESS ] }
    - { path: ^/v2/countries, roles: [ PUBLIC_ACCESS ] }
    - { path: ^/v2/missing, roles: [ PUBLIC_ACCESS ] }
    - { path: ^/v2/report, roles: [ PUBLIC_ACCESS ] }
    - { path: ^/v3/polls, roles: [ ROLE_FIREBASE_USER ] }
    - { path: ^/v3/users, roles: [ ROLE_FIREBASE_USER ] }
    - { path: ^/v\d+/holiday, roles: [ PUBLIC_ACCESS ] }
    - { path: ^/, roles: [ ROLE_USER ] }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'plaintext'
