services:
  App\Service\FirebaseTokenVerifier:
    class: App\Tests\Double\TestFirebaseTokenVerifier

  App\Service\FirebaseUserLookup:
    class: App\Tests\Double\TestFirebaseUserLookup

  Symfony\Contracts\HttpClient\HttpClientInterface:
    public: true
